### ISSUE TITLE
Cannot Build with MSVC Compiler 14 (Visual Studio 2019)

### ISSUE THREAD

**Issue by wmfkunzi** [secure-dev-ops/code-realtime#15]
I run into issue while trying to compile the HelloWorld sample with Visual Studio 2019 compiler and it is a little bit strange.
I try to describe it.

The TargetRTS I can build with my "normal" build script, include path are inside via [setup.pl](https://urldefense.com/v3/__http://setup.pl__;!!K62b8Q!O5GZp4Nam4bZ3LYtPskXaGfSccznYJhsWerEMb4K_Pmc-Fg_9WllPUSOGrrG95oAhHVeQLaimfigUHiDNeSiB1kaqSink1q1$) file.

While trying to build it always says: 
____
cl /c  /FoA.OBJ  /nologo /EHsc /GF /MD /TP    /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/libset/x64-VisualC++-19.0"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/target/WinT"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include" /std:c++17 /I.. ..\A.cpp
A.cpp
C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include\RTnew.h(21): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "new": No such file or directory
____

The reason is that the input path for the windows sources are missing (they will not be added out of the setup of RTS build scripts).
So I manually added with the inclusion path option in the tcjs-file the inclusion path manually.
Strange thing is if I look to the /I option in the command line.
If I add it like this:
![1](https://github.com/user-attachments/assets/01c6e12b-adeb-49d4-86ee-7cf997c20d16)
![2](https://github.com/user-attachments/assets/97718cdf-613e-4874-a719-2d7b695cd509)

It will result as well in a compiler error, because the "" are missing after the /I.
____
cl /c  /FoA.OBJ  /nologo /EHsc /GF /MD /TP    /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/libset/x64-VisualC++-19.0"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/target/WinT"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include" /std:c++17 /I.. /IC:\PROGRA~2\MIB055~1\2019\ENTERP~1\VCTools\MSVC\1429~1.301\include ..\A.cpp
A.cpp
C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include\RTnew.h(21): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "new": No such file or directory
____

If I add it like this:
![3](https://github.com/user-attachments/assets/4efcca2e-af3c-4de7-9700-e0a4ce61396b)
![4](https://github.com/user-attachments/assets/1f175fd8-134f-4e17-a0f2-f4b2c83aef50)

It will result that the include path will be igored.
_____
cl /c  /FoA.OBJ  /nologo /EHsc /GF /MD /TP    /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/libset/x64-VisualC++-19.0"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/target/WinT"  /I"C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include" /std:c++17 /I.. ..\A.cpp
A.cpp
C:/Users/xxx/.vscode/extensions/secure-dev-ops.code-realtime-1.0.4/TargetRTS/include\RTnew.h(21): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "new": No such file or directory
_____

Many thanks in advance for investigation...

**Comment by wmfkunzi** [comment]
Thank you Alexander and Elena for your quick and uncomplicated support.
To the issue described above there are two reason why it not will compile.
The first reason is that in the inclusion path was a typo: "..\\VC\\Tools\\.." is the correct one.
The second reason for unable to compile was that the VSCode should be opened through the Visual Studio Native Tools Command Prompt to get all the necessary environment variables handled over to it.
Alexander: Please be so patient to write a final comment and close this issue.
Best Regards,
Ingo

**Comment by astrabykin** [comment]
Thanks, Ingo! Closing the issue now as you are not blocked anymore.
